routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BlogCategoryController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\BranchTypeController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ChatController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DayController;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\GovernorateController;
use App\Http\Controllers\Admin\JoinUsController;
use App\Http\Controllers\Admin\LanguageController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\OurPartnerController;
use App\Http\Controllers\Admin\OwnerController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\RatesController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ShopController;
use App\Http\Controllers\Admin\SocialMediaController;
use App\Http\Controllers\Admin\VehicleTypesController;
use App\Http\Controllers\Dashboard\DiscountController;
use Illuminate\Support\Facades\Route;

Route::middleware(['guest:admin'])->controller(AuthController::class)->group(function () {
    Route::get('/', fn() => redirect()->route('dashboard'));
    Route::get('login', 'showLoginForm')->name('login');
    Route::post('login', 'login')->name('login');
    Route::get('rest/password', 'resetPassword')->name('reset.password');
    Route::post('rest/password', 'postResetPassword')->name('reset.password');
    Route::get('rest/password/{token}', 'reset')->name('reset');
    Route::post('rest/password/{token}', 'postReset')->name('reset');
});

Route::middleware(['auth:admin', 'check-status-admin'])->group(function () {
    Route::redirect('/admin', '/admin/dashboard');

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('/per', [DashboardController::class, 'permissionAdmin']);

    /* profile */ // not working
    Route::prefix('profile')->name('profile.')->controller(AuthController::class)->group(function () {
        Route::get('account', 'profile')->name('account');
        Route::post('account', 'storeProfile')->name('account');
        Route::post('change-password', 'changePassword')->name('change-password');
    });

    /* role */
    Route::resource('role', RoleController::class)->except(['show', 'destroy']);
    Route::post('role/destroy/{id}', [RoleController::class, 'destroy'])->name('role.destroy');


    /* staff alis employee super admin */
    Route::prefix('employee')->name('employee.')->controller(EmployeeController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('change-password', 'changePassword')->name('change-password');
    });
    Route::resource('employee', EmployeeController::class)->except(['show', 'destroy']);

    /* language */
    Route::prefix('language')->name('language.')->controller(LanguageController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('update-default', 'updateDefaultStatus')->name('update-default');
        Route::get('translate/{lang}', 'translate')->name('translate');
        Route::post('translate-submit/{lang}', 'translate_submit')->name('translate-submit');
    });
    Route::resource('language', LanguageController::class);

    /* setting */
    Route::prefix('setting')->name('setting.')->controller(SettingController::class)->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::post('email', 'saveEmailSettings')->name('email');
        Route::post('test-mail', 'testSendMail')->name('send-mail');
        Route::post('pusher', 'savePusherSettings')->name('pusher');
    });

    /* day */
    Route::resource('day', DayController::class)->except(['show', 'store', 'destroy']);

    /* pages */

    Route::resource('page', PageController::class)->except(['show', 'destroy']);
    Route::prefix('page')->name('page.')->controller(PageController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::get('destroy/{id}', 'destroy')->name('destroy');
    });
    /* coupon */
    Route::prefix('coupon')->name('coupon.')->controller(CouponController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('coupon', CouponController::class)->except(['show']);
    /* services */
    Route::prefix('service')->name('service.')->controller(ServiceController::class)->group(function () {
        Route::post('/update-status', 'updateStatus')->name('update-status');
        Route::post('/delete-image', 'deleteImage')->name('delete-image');
    });
    Route::resource('service', ServiceController::class)->except(['destroy']);
    /* currency */
    Route::resource('currency', CurrencyController::class)->except(['show']);
    Route::post('currency/update-status', [CurrencyController::class, 'updateStatus'])->name('currency.update-status');

    /* country */
    Route::resource('country', CountryController::class)->except(['show']);
    Route::post('country/update-status', [CountryController::class, 'updateStatus'])->name('country.update-status');

    /* governorate */
    Route::post('governorate/update-status', [GovernorateController::class, 'updateStatus'])->name('governorate.update-status');
    Route::resource('governorate', GovernorateController::class)->except(['show']);

    /* regions */
    Route::post('region/update-status', [RegionController::class, 'updateStatus'])->name('region.update-status');
    Route::resource('region', RegionController::class)->except(['show']);

    /* branch-type */
    Route::prefix('branch-type')->name('branch-type.')->controller(BranchTypeController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('update-published', 'updatePublished')->name('update-published');
    });
    Route::resource('branch-type', BranchTypeController::class)->except(['show', 'destroy']);

    /* category */
    Route::prefix('category')->name('category.')->controller(CategoryController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('category', CategoryController::class)->except(['show', 'destroy']);
    /* company */
    Route::prefix('company')->name('company.')->controller(CompanyController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('company', CompanyController::class)->except(['show', 'destroy']);
    /* owners */
    Route::prefix('owner')->name('owner.')->controller(OwnerController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('change-password', 'changePassword')->name('change-password');
    });
    Route::resource('owner', OwnerController::class)->except(['destroy']);

    /* customer */
    Route::controller(CustomerController::class)->prefix('customer')->name('customer.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/show/{id}', 'show')->name('show');
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::get('export-excel', 'export')->name('export-excel');
        Route::post('change-password', 'changePassword')->name('change-password');



    });
    /* rate */
    Route::get('rate/delete/{id}', [RatesController::class, 'destroy'])->name('rate.destroy');
    Route::resource('rate', RatesController::class)->except(['destroy']);
    Route::prefix('rate')->name('rate.')->group(function () {
        Route::post('rate/update-status', [RatesController::class, 'updateStatus'])->name('update-status');

    });

    /* contact us */
    Route::resource('contact-us', ContactUsController::class)->except(['show', 'destroy']);
    Route::get('contact-us/{id}', [ContactUsController::class, 'destroy'])->name('contact-us.destroy');
    /* our-partner */
    Route::prefix('our-partner')->name('our-partner.')->controller(OurPartnerController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('our-partner', OurPartnerController::class)->except(['destroy']);
    /* shop */
    Route::prefix('shop')->name('shop.')->controller(ShopController::class)->group(function () {
        Route::post('/update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('shop', ShopController::class)->except(['destroy']);

    /* testing */





    /* banners */
    Route::prefix('banner')->name('banner.')->controller(BannerController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('banner', BannerController::class)->except(['destroy']);
    /* social media */
    Route::prefix('social-media')->name('social-media.')->controller(SocialMediaController::class)->group(function () {

routes/web.php
<?php

use App\Http\Controllers\Admin\ShopController;
use App\Http\Controllers\Dashboard\AuthController;
use App\Http\Controllers\Dashboard\DeliveryAreaController;
use App\Http\Controllers\Dashboard\DiscountController;
use App\Http\Controllers\Dashboard\DriverController;
use App\Http\Controllers\Dashboard\DriverOrderController;
use App\Http\Controllers\Dashboard\HomeController;
use App\Http\Controllers\Dashboard\LiveChatController;
use App\Http\Controllers\Dashboard\OfferController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\ProductController;
use App\Http\Controllers\Dashboard\RoleController;
use App\Http\Controllers\Dashboard\SaveController;
use App\Http\Controllers\Dashboard\StaffController;
use Illuminate\Support\Facades\Route;

Route::get('share-url', [HomeController::class, 'getSharedLinkPreview'])->name('link-preview');
Route::get('download-app', function () {
    return view('download-app');
})->name('download-app');
Route::get('lang/{locale}/{guard?}', [HomeController::class, 'language'])->name('lang');

Route::middleware(['auth:web,admin', 'auth', 'auth-user'])->group(function () {
    Route::get('role/destroy/{id}', [RoleController::class, 'destroy'])->name('role.destroy');
    Route::resource('role', RoleController::class)->except(['show', 'destroy']);

    /* staff shop */
    Route::prefix('staff')->name('staff.')->controller(StaffController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('change-password', 'changePassword')->name('change-password');
    });
    Route::resource('staff', StaffController::class)->except(['show', 'destroy']);
    /* delivery areas */
    Route::post('delivery-area/update-status', [DeliveryAreaController::class, 'updateStatus'])->name('delivery-area.update-status');
    Route::resource('delivery-area', DeliveryAreaController::class)->except(['show']);
    Route::post('area/update-status', [DeliveryAreaController::class, 'updateAreaStatus'])->name('area.update-status');

    /* orders */
    Route::controller(OrderController::class)->prefix('order')->name('order.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/show/{id}/{notificationId?}', 'show')->name('show');
        Route::get('/update-status/{orderId}', 'updateStatus')->name('update-status');
        Route::post('/cancelled/{orderId}', 'updateStatus')->name('cancelled');
        Route::post('/returned/{orderId}', 'updateStatus')->name('returned');
        Route::post('/assign-driver/{orderId}', 'updateStatus')->name('assign-driver');

    });
    /* products */
    Route::prefix('product')->name('product.')->controller(ProductController::class)->group(function () {
        Route::post('/update-status', 'updateStatus')->name('update-status');
        Route::post('/update-wanted', 'updateWanted')->name('update-wanted');
        Route::post('/delete-size', 'deleteSize')->name('delete-size');
        Route::post('/delete-image', 'deleteImage')->name('delete-image');
    });
    Route::resource('product', ProductController::class)->except(['destroy']);
    Route::post('color/update-status', [ProductController::class, 'updateColorStatus'])->name('color.update-status');
    /* offers */
    Route::prefix('offer')->name('offer.')->controller(OfferController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('/delete-image', 'deleteImage')->name('delete-image');
    });
    Route::resource('offer', OfferController::class)->except(['destroy']);
    /* saves */
    Route::prefix('save')->name('save.')->controller(SaveController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('/delete-image', 'deleteImage')->name('delete-image');
    });
    Route::resource('save', SaveController::class)->except(['destroy']);
    /* discounts */
    Route::prefix('discount')->name('discount.')->controller(DiscountController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('discount', DiscountController::class)->except(['destroy']);
    /* driver */
    Route::prefix('driver')->name('driver.')->controller(DriverController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('change-password', 'changePassword')->name('change-password');
    });
    Route::resource('driver', DriverController::class);
    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/information', [AuthController::class, 'profile'])->name('information');
        Route::post('/submit-information', [AuthController::class, 'storeProfile'])->name('submit-information');
        Route::post('change-password', [AuthController::class, 'changePassword'])->name('change-password');
    });
    Route::prefix('driver-order')->name('driver-order.')->controller(DriverOrderController::class)->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/create', 'store')->name('store');
        Route::get('/edit/{id}', 'edit')->name('edit');
        Route::post('/update', 'update')->name('update');
    });
    Route::controller(LiveChatController::class)->name('live-chat.')->prefix('live-chat')
        ->group(function () {
            Route::get('index/{shopId?}/{conversionId?}', 'index')->name('index');
            Route::get('conversations', 'conversations')->name('conversations');
            Route::post('store', 'store')->name('store');
            Route::get('show', 'show')->name('show');
        });

});
Route::middleware(['guest'])->group(function () {
    Route::get('/', function () {
        return redirect()->route('admin.login');
    });
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('rest/password', [\App\Http\Controllers\Auth\AuthController::class, 'resetPassword'])->name('get.reset.password');
        Route::post('rest/password', [\App\Http\Controllers\Auth\AuthController::class, 'postResetPassword'])->name('reset.password');
        Route::get('rest/password/{token}', [\App\Http\Controllers\Auth\AuthController::class, 'getReset'])->name('reset');
        Route::post('rest/password/{token}', [\App\Http\Controllers\Auth\AuthController::class, 'postReset'])->name('reset');
    });
});
Route::get('qr-code/{filename}', [ShopController::class, 'downloadQrCode'])->name('download.qr-code');
Route::get('/per', [\App\Http\Controllers\Admin\DashboardController::class, 'permissionAdmin']);
Route::get('/owner-per', [\App\Http\Controllers\Admin\DashboardController::class, 'permissionOwner']);

resources/views/dashboard/discount/index.blade.php
@extends('layouts.master')
@section('title',_trans('Discounts'))
@section('content')
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6 col-sm-6">
                    <h3>{{ _trans('Discounts') }}</h3>
                </div>
                @can('Discount add')
                    <div class="col-6 text-right">
                        <a href="{{ route('discount.create') }}" class="btn btn-primary">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        </a>
                    </div>
                @endcan

            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid default-dash">
        <div class="row">
            <div class="col-12 col-sm-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.dashboard') }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round" class="feather feather-home">
                                <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                                <polyline points="9 22 9 12 15 12 15 22"></polyline>
                            </svg>
                        </a></li>
                    <li class="breadcrumb-item active">{{ _trans('Discounts') }}</li>
                </ol>
            </div>

            <div class="col-xl-12 col-md-12 ">

                <form action="{{ url()->current() }}" method="GET">
                    <div class="left-side-header">
                        <div class="row justify-content-between align-items-center">
                            <x-search :columns="$columns"/>
                            <div class="col-md-4">
                                <p class="mb-0 font-sm d-flex align-items-center justify-content-end">{{ _trans('Count Discounts') }}
                                    :
                                    <span class="d-block font-md text-danger">({{ $data->total() }})</span>
                                </p>
                            </div>
                        </div>
                    </div>
                </form>


                <div class="table-responsive custom-scrollbar p-t-30">
                    <table class="table">
                        <thead>
                        <tr>
                            <th><span>{{ _trans('Code')}} </span></th>
                            @if (request('guard')=='admin')
                            <th><span>{{ _trans('Owner name')}}</span></th>
                            @endif
                            <th><span>{{ _trans('Shop name')}}</span></th>
                            <th><span>{{ _trans('Product name')}}</span></th>
                            <th><span>{{ _trans('Price Before')}}</span></th>
                            <th><span>{{ _trans('Price After')}}</span></th>
                            <th><span>{{ _trans('Start')}}</span></th>
                            <th><span>{{ _trans('End')}}</span></th>
                            <th><span>{{ _trans('Status')}}</span></th>
                            <th><span>{{ _trans('action')}}</span></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $key => $row)
                            <tr>
                                <td class="text-main">Discount#{{ $row->id }}</td>
                                @if (request('guard')=='admin')
                                <td>{{  $row->owner->user->name  }}</td>
                                @endif
                                <td>
                                    <a href="{{ route('admin.shop.index').'/?shop='.$row->shop->translate(locale())?->name }}">
                                        {{  $row->shop->translate(locale())?->name  }}
                                    </a>
                                </td>
                                <td>{{ $row->product->translate(locale())?->name  }}</td>
                                <td>{{ $row->price_before }}</td>
                                <td>{{ $row->price_after }}</td>
                                <td>{{ formatDate('d-m-Y',$row->start) }}</td>
                                <td>{{ formatDate('d-m-Y',$row->end) }}</td>
                                <td>
                                    <div class="media-body icon-state">
                                        <label class="switch">
                                            <input id="{{ $row->id }}" type="checkbox"
                                                   class="status" @checked($row->status == 1) >
                                            <span class="switch-state "></span>
                                        </label>
                                    </div>
                                </td>

                                <td>
                                    @can('Discount list')
                                        <a href="{{ route('discount.show',$row->id) }}" class="btn btn-primary">
                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                        </a>
                                    @endcan
                                    @can('Discount edit')
                                        <a href="{{ route('discount.edit',$row->id) }}" class="btn btn-primary">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

                {{ $data->appends(request()->query())->links('layouts.partials.pagination') }}

                @if( $data->count() == 0)
                    <div class="empty-data">
                        <img src="{{ asset('assets')}}/images/nodata.svg">
                        <h4>{{ _trans('No_data_to_show')}}</h4>
                    </div>
                @endif
            </div>

        </div>
    </div>
    <!-- Container-fluid Ends-->
@endsection

@include('layouts.ajax.update-status',['class' => 'status','route' => route('discount.update-status')])

resources/views/dashboard/discount/show.blade.php
@extends('layouts.master')
@section('title',_trans('Discounts'))
@section('content')

        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-6 col-sm-6">
                        <h3>{{ _trans('Discount Details') }}</h3>
                    </div>
                    <div class="col-6 text-right">

                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid default-dash">
            <div class="row">

                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card card-details">
                                <h4 class="title-details">{{_trans('Discount Details')}}</h4>
                                <div class="">
                                    <p>{{_trans('Product')}} :<span>{{$discount->product->translate(locale())?->name}}</span></p>
                                    <p>{{_trans('Shop')}} :<span>{{$discount->shop->translate(locale())?->name}}</span></p>
                                    <p>{{_trans('Start')}} :<span>{{$discount->start}}</span></p>
                                    <p>{{_trans('End')}} :<span>{{$discount->end}}</span></p>
                                    <p>{{_trans('Price Before')}} :<span>{{$discount->price_before}}</span></p>
                                    <p>{{_trans('Percent')}} :<span>{{$discount->percent}}</span></p>
                                    <p>{{_trans('Price After')}} :<span>{{$discount->price_after}}</span></p>

                                    <p>{{_trans('Icon')}} : <span>
                                  <img class="mb-2 image-preview" src="{{getAvatar($discount->product->icon)}}">
                              </span></p>

                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="card card-details">
                                <h4 class="title-details">{{ _trans('Orders')}}</h4>
                                <div class="">
                                    <p>{{ _trans('Count')}} : <span>{{$orders->count()}}</span></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
        <!-- Container-fluid Ends-->

@endsection