routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BlogCategoryController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\BranchTypeController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ChatController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DayController;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\GovernorateController;
use App\Http\Controllers\Admin\JoinUsController;
use App\Http\Controllers\Admin\LanguageController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\OurPartnerController;
use App\Http\Controllers\Admin\OwnerController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\RatesController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ShopController;
use App\Http\Controllers\Admin\SocialMediaController;
use App\Http\Controllers\Admin\VehicleTypesController;
use App\Http\Controllers\Dashboard\DiscountController;
use Illuminate\Support\Facades\Route;

Route::middleware(['guest:admin'])->controller(AuthController::class)->group(function () {
    Route::get('/', fn() => redirect()->route('dashboard'));
    Route::get('login', 'showLoginForm')->name('login');
    Route::post('login', 'login')->name('login');
    Route::get('rest/password', 'resetPassword')->name('reset.password');
    Route::post('rest/password', 'postResetPassword')->name('reset.password');
    Route::get('rest/password/{token}', 'reset')->name('reset');
    Route::post('rest/password/{token}', 'postReset')->name('reset');
});

Route::middleware(['auth:admin', 'check-status-admin'])->group(function () {
    Route::redirect('/admin', '/admin/dashboard');

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('/per', [DashboardController::class, 'permissionAdmin']);

    /* profile */ // not working
    Route::prefix('profile')->name('profile.')->controller(AuthController::class)->group(function () {
        Route::get('account', 'profile')->name('account');
        Route::post('account', 'storeProfile')->name('account');
        Route::post('change-password', 'changePassword')->name('change-password');
    });

    /* role */
    Route::resource('role', RoleController::class)->except(['show', 'destroy']);
    Route::post('role/destroy/{id}', [RoleController::class, 'destroy'])->name('role.destroy');


    /* staff alis employee super admin */
    Route::prefix('employee')->name('employee.')->controller(EmployeeController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('change-password', 'changePassword')->name('change-password');
    });
    Route::resource('employee', EmployeeController::class)->except(['show', 'destroy']);

    /* language */
    Route::prefix('language')->name('language.')->controller(LanguageController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('update-default', 'updateDefaultStatus')->name('update-default');
        Route::get('translate/{lang}', 'translate')->name('translate');
        Route::post('translate-submit/{lang}', 'translate_submit')->name('translate-submit');
    });
    Route::resource('language', LanguageController::class);

    /* setting */
    Route::prefix('setting')->name('setting.')->controller(SettingController::class)->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::post('email', 'saveEmailSettings')->name('email');
        Route::post('test-mail', 'testSendMail')->name('send-mail');
        Route::post('pusher', 'savePusherSettings')->name('pusher');
    });

    /* day */
    Route::resource('day', DayController::class)->except(['show', 'store', 'destroy']);

    /* pages */

    Route::resource('page', PageController::class)->except(['show', 'destroy']);
    Route::prefix('page')->name('page.')->controller(PageController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::get('destroy/{id}', 'destroy')->name('destroy');
    });
    /* coupon */
    Route::prefix('coupon')->name('coupon.')->controller(CouponController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('coupon', CouponController::class)->except(['show']);
    /* services */
    Route::prefix('service')->name('service.')->controller(ServiceController::class)->group(function () {
        Route::post('/update-status', 'updateStatus')->name('update-status');
        Route::post('/delete-image', 'deleteImage')->name('delete-image');
    });
    Route::resource('service', ServiceController::class)->except(['destroy']);
    /* currency */
    Route::resource('currency', CurrencyController::class)->except(['show']);
    Route::post('currency/update-status', [CurrencyController::class, 'updateStatus'])->name('currency.update-status');

    /* country */
    Route::resource('country', CountryController::class)->except(['show']);
    Route::post('country/update-status', [CountryController::class, 'updateStatus'])->name('country.update-status');

    /* governorate */
    Route::post('governorate/update-status', [GovernorateController::class, 'updateStatus'])->name('governorate.update-status');
    Route::resource('governorate', GovernorateController::class)->except(['show']);

    /* regions */
    Route::post('region/update-status', [RegionController::class, 'updateStatus'])->name('region.update-status');
    Route::resource('region', RegionController::class)->except(['show']);

    /* branch-type */
    Route::prefix('branch-type')->name('branch-type.')->controller(BranchTypeController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('update-published', 'updatePublished')->name('update-published');
    });
    Route::resource('branch-type', BranchTypeController::class)->except(['show', 'destroy']);

    /* category */
    Route::prefix('category')->name('category.')->controller(CategoryController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('category', CategoryController::class)->except(['show', 'destroy']);
    /* company */
    Route::prefix('company')->name('company.')->controller(CompanyController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('company', CompanyController::class)->except(['show', 'destroy']);
    /* owners */
    Route::prefix('owner')->name('owner.')->controller(OwnerController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('change-password', 'changePassword')->name('change-password');
    });
    Route::resource('owner', OwnerController::class)->except(['destroy']);

    /* customer */
    Route::controller(CustomerController::class)->prefix('customer')->name('customer.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/show/{id}', 'show')->name('show');
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::get('export-excel', 'export')->name('export-excel');
        Route::post('change-password', 'changePassword')->name('change-password');



    });
    /* rate */
    Route::get('rate/delete/{id}', [RatesController::class, 'destroy'])->name('rate.destroy');
    Route::resource('rate', RatesController::class)->except(['destroy']);
    Route::prefix('rate')->name('rate.')->group(function () {
        Route::post('rate/update-status', [RatesController::class, 'updateStatus'])->name('update-status');

    });

    /* contact us */
    Route::resource('contact-us', ContactUsController::class)->except(['show', 'destroy']);
    Route::get('contact-us/{id}', [ContactUsController::class, 'destroy'])->name('contact-us.destroy');
    /* our-partner */
    Route::prefix('our-partner')->name('our-partner.')->controller(OurPartnerController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('our-partner', OurPartnerController::class)->except(['destroy']);
    /* shop */
    Route::prefix('shop')->name('shop.')->controller(ShopController::class)->group(function () {
        Route::post('/update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('shop', ShopController::class)->except(['destroy']);

    /* testing */





    /* banners */
    Route::prefix('banner')->name('banner.')->controller(BannerController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('banner', BannerController::class)->except(['destroy']);
    /* social media */
    Route::prefix('social-media')->name('social-media.')->controller(SocialMediaController::class)->group(function () {

routes/web.php
<?php

use App\Http\Controllers\Admin\ShopController;
use App\Http\Controllers\Dashboard\AuthController;
use App\Http\Controllers\Dashboard\DeliveryAreaController;
use App\Http\Controllers\Dashboard\DiscountController;
use App\Http\Controllers\Dashboard\DriverController;
use App\Http\Controllers\Dashboard\DriverOrderController;
use App\Http\Controllers\Dashboard\HomeController;
use App\Http\Controllers\Dashboard\LiveChatController;
use App\Http\Controllers\Dashboard\OfferController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\ProductController;
use App\Http\Controllers\Dashboard\RoleController;
use App\Http\Controllers\Dashboard\SaveController;
use App\Http\Controllers\Dashboard\StaffController;
use Illuminate\Support\Facades\Route;

Route::get('share-url', [HomeController::class, 'getSharedLinkPreview'])->name('link-preview');
Route::get('download-app', function () {
    return view('download-app');
})->name('download-app');
Route::get('lang/{locale}/{guard?}', [HomeController::class, 'language'])->name('lang');

Route::middleware(['auth:web,admin', 'auth', 'auth-user'])->group(function () {
    Route::get('role/destroy/{id}', [RoleController::class, 'destroy'])->name('role.destroy');
    Route::resource('role', RoleController::class)->except(['show', 'destroy']);

    /* staff shop */
    Route::prefix('staff')->name('staff.')->controller(StaffController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('change-password', 'changePassword')->name('change-password');
    });
    Route::resource('staff', StaffController::class)->except(['show', 'destroy']);
    /* delivery areas */
    Route::post('delivery-area/update-status', [DeliveryAreaController::class, 'updateStatus'])->name('delivery-area.update-status');
    Route::resource('delivery-area', DeliveryAreaController::class)->except(['show']);
    Route::post('area/update-status', [DeliveryAreaController::class, 'updateAreaStatus'])->name('area.update-status');

    /* orders */
    Route::controller(OrderController::class)->prefix('order')->name('order.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/show/{id}/{notificationId?}', 'show')->name('show');
        Route::get('/update-status/{orderId}', 'updateStatus')->name('update-status');
        Route::post('/cancelled/{orderId}', 'updateStatus')->name('cancelled');
        Route::post('/returned/{orderId}', 'updateStatus')->name('returned');
        Route::post('/assign-driver/{orderId}', 'updateStatus')->name('assign-driver');

    });
    /* products */
    Route::prefix('product')->name('product.')->controller(ProductController::class)->group(function () {
        Route::post('/update-status', 'updateStatus')->name('update-status');
        Route::post('/update-wanted', 'updateWanted')->name('update-wanted');
        Route::post('/delete-size', 'deleteSize')->name('delete-size');
        Route::post('/delete-image', 'deleteImage')->name('delete-image');
    });
    Route::resource('product', ProductController::class)->except(['destroy']);
    Route::post('color/update-status', [ProductController::class, 'updateColorStatus'])->name('color.update-status');
    /* offers */
    Route::prefix('offer')->name('offer.')->controller(OfferController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('/delete-image', 'deleteImage')->name('delete-image');
    });
    Route::resource('offer', OfferController::class)->except(['destroy']);
    /* saves */
    Route::prefix('save')->name('save.')->controller(SaveController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('/delete-image', 'deleteImage')->name('delete-image');
    });
    Route::resource('save', SaveController::class)->except(['destroy']);
    /* discounts */
    Route::prefix('discount')->name('discount.')->controller(DiscountController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
    });
    Route::resource('discount', DiscountController::class)->except(['destroy']);
    /* driver */
    Route::prefix('driver')->name('driver.')->controller(DriverController::class)->group(function () {
        Route::post('update-status', 'updateStatus')->name('update-status');
        Route::post('change-password', 'changePassword')->name('change-password');
    });
    Route::resource('driver', DriverController::class);
    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/information', [AuthController::class, 'profile'])->name('information');
        Route::post('/submit-information', [AuthController::class, 'storeProfile'])->name('submit-information');
        Route::post('change-password', [AuthController::class, 'changePassword'])->name('change-password');
    });
    Route::prefix('driver-order')->name('driver-order.')->controller(DriverOrderController::class)->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/create', 'store')->name('store');
        Route::get('/edit/{id}', 'edit')->name('edit');
        Route::post('/update', 'update')->name('update');
    });
    Route::controller(LiveChatController::class)->name('live-chat.')->prefix('live-chat')
        ->group(function () {
            Route::get('index/{shopId?}/{conversionId?}', 'index')->name('index');
            Route::get('conversations', 'conversations')->name('conversations');
            Route::post('store', 'store')->name('store');
            Route::get('show', 'show')->name('show');
        });

});
Route::middleware(['guest'])->group(function () {
    Route::get('/', function () {
        return redirect()->route('admin.login');
    });
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('rest/password', [\App\Http\Controllers\Auth\AuthController::class, 'resetPassword'])->name('get.reset.password');
        Route::post('rest/password', [\App\Http\Controllers\Auth\AuthController::class, 'postResetPassword'])->name('reset.password');
        Route::get('rest/password/{token}', [\App\Http\Controllers\Auth\AuthController::class, 'getReset'])->name('reset');
        Route::post('rest/password/{token}', [\App\Http\Controllers\Auth\AuthController::class, 'postReset'])->name('reset');
    });
});
Route::get('qr-code/{filename}', [ShopController::class, 'downloadQrCode'])->name('download.qr-code');
Route::get('/per', [\App\Http\Controllers\Admin\DashboardController::class, 'permissionAdmin']);
Route::get('/owner-per', [\App\Http\Controllers\Admin\DashboardController::class, 'permissionOwner']);

resources/views/dashboard/panel/header.blade.php
<div class="header-wrapper row m-0">
    <div class="header-logo-wrapper col-2 p-0">
        <div class="logo-wrapper"><a href="{{ route('owner.dashboard') }}">
                <img src="{{ Utility::getValByName('web_logo') }}"></a>
        </div>
        <div class="toggle-sidebar">
            <div class="status_toggle sidebar-toggle d-flex">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g>
                        <g>
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M21.0003 6.6738C21.0003 8.7024 19.3551 10.3476 17.3265 10.3476C15.2979 10.3476 13.6536 8.7024 13.6536 6.6738C13.6536 4.6452 15.2979 3 17.3265 3C19.3551 3 21.0003 4.6452 21.0003 6.6738Z"
                                  stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M10.3467 6.6738C10.3467 8.7024 8.7024 10.3476 6.6729 10.3476C4.6452 10.3476 3 8.7024 3 6.6738C3 4.6452 4.6452 3 6.6729 3C8.7024 3 10.3467 4.6452 10.3467 6.6738Z"
                                  stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M21.0003 17.2619C21.0003 19.2905 19.3551 20.9348 17.3265 20.9348C15.2979 20.9348 13.6536 19.2905 13.6536 17.2619C13.6536 15.2333 15.2979 13.5881 17.3265 13.5881C19.3551 13.5881 21.0003 15.2333 21.0003 17.2619Z"
                                  stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M10.3467 17.2619C10.3467 19.2905 8.7024 20.9348 6.6729 20.9348C4.6452 20.9348 3 19.2905 3 17.2619C3 15.2333 4.6452 13.5881 6.6729 13.5881C8.7024 13.5881 10.3467 15.2333 10.3467 17.2619Z"
                                  stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        </g>
                    </g>
                </svg>
            </div>
        </div>
    </div>

    <div class="nav-right col-10 pull-right right-header p-0">
        <ul class="nav-menus">
            {{-- is components --}}
            <x-language guard="web"/>

            @canany(['Notification list','Notification add'])
                @php
                    $notifications = getNotificationOwners(['order','account_order','message','invoice','live-chat']);
                @endphp
                <li class="onhover-dropdown">
                    <div class="notification-box">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g>
                                <g>
                                    <path fill-rule="evenodd" clip-rule="evenodd"
                                          d="M11.9961 2.51416C7.56185 2.51416 5.63519 6.5294 5.63519 9.18368C5.63519 11.1675 5.92281 10.5837 4.82471 13.0037C3.48376 16.4523 8.87614 17.8618 11.9961 17.8618C15.1152 17.8618 20.5076 16.4523 19.1676 13.0037C18.0695 10.5837 18.3571 11.1675 18.3571 9.18368C18.3571 6.5294 16.4295 2.51416 11.9961 2.51416Z"
                                          stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path d="M14.306 20.5122C13.0117 21.9579 10.9927 21.9751 9.68604 20.5122" stroke="#130F26"
                                          stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                </g>
                            </g>
                        </svg>
                        <span class="badge rounded-pill badge-warning" id="notification_owner">
                    {{ $notifications->count() }}
                    </span>
                    </div>
                    <div class="onhover-show-div notification-dropdown">
                        <div class="dropdown-title">
                            <h3>{{ _trans('Notifications') }}</h3><a class="f-right" href="#"> <i data-feather="bell"> </i></a>
                        </div>
                        <ul class="custom-scrollbar" id="notification_list_owner">
                            @foreach($notifications as $row)
                                <li id="notificationId_{{ $row->id }}">
                                    <div class="media">
                                        <div class="notification-img bg-light-success">
                                            <img src="{{ getAvatar($row->customer->user->avatar) }}" alt="" style="height: 20px;width: 20px;">
                                        </div>
                                        <div class="media-body">
                                            <h5>
                                                @if ($row->type == 'order' || $row->type == 'account_order')
                                                    <a class="f-14 m-0" href="{{ route('order.show',[$row->data['order_id'],$row->id]) }}">
                                                        {{ $row->customer->user->name }}
                                                    </a>
                                                @elseif ($row->type =='message')
                                                    <a class="f-14 m-0">
                                                        {{ _trans('Message from ').$row->customer->user->name }}
                                                    </a>
                                                @elseif($row->type =='live-chat')

                                                    <a href="{{ route('live-chat.index',[$row->data['shop_id'],$row->data['conversion_id']]) }}" class="f-14 m-0">
                                                        {{ _trans('Message live chat').' '.$row->customer?->user?->name }}
                                                    </a>
                                                @endif
                                            </h5>
                                            @if ($row->type == 'order' || $row->type == 'account_order')
                                                <p>{{ _trans('request order new') }}</p><span>{{ $row->created_at->diffForHumans() }}</span>
                                            @elseif ($row->type =='message')
                                                <p>{{ _trans('new message') }}</p><span>{{ $row->created_at->diffForHumans() }}</span>
                                            @elseif($row->type =='live-chat')
                                                <p>{{ _trans('new live chat') }}</p><span>{{ $row->created_at->diffForHumans() }}</span>
                                            @endif
                                        </div>
{{--                                        <div class="notification-right">--}}
{{--                                            <a href="#" onclick="deleteNotification(event,{{$row->id}})" id="deleteNotification">--}}
{{--                                                <i data-feather="x"></i>--}}
{{--                                            </a>--}}
{{--                                        </div>--}}
                                    </div>
                                </li>
                            @endforeach
                        </ul>

                        <a class="btn btn-primary btn-check-all" href="{{ route('owner.notification.index') }}">{{ _trans('Check all') }}</a>
                    </div>
                </li>
            @endcanany

            <li class="profile-nav onhover-dropdown">
                <div class="media profile-media">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g>
                            <g>
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M9.55851 21.4562C5.88651 21.4562 2.74951 20.9012 2.74951 18.6772C2.74951 16.4532 5.86651 14.4492 9.55851 14.4492C13.2305 14.4492 16.3665 16.4342 16.3665 18.6572C16.3665 20.8802 13.2505 21.4562 9.55851 21.4562Z"
                                      stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M9.55849 11.2776C11.9685 11.2776 13.9225 9.32356 13.9225 6.91356C13.9225 4.50356 11.9685 2.54956 9.55849 2.54956C7.14849 2.54956 5.19449 4.50356 5.19449 6.91356C5.18549 9.31556 7.12649 11.2696 9.52749 11.2776H9.55849Z"
                                      stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                <path
                                    d="M16.8013 10.0789C18.2043 9.70388 19.2383 8.42488 19.2383 6.90288C19.2393 5.31488 18.1123 3.98888 16.6143 3.68188"
                                    stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                <path
                                    d="M17.4608 13.6536C19.4488 13.6536 21.1468 15.0016 21.1468 16.2046C21.1468 16.9136 20.5618 17.6416 19.6718 17.8506"
                                    stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            </g>
                        </g>
                    </svg>
                </div>
                <ul class="profile-dropdown onhover-show-div">
                    <li><a href="{{ route('owner.profile.account') }}"><i data-feather="user"></i><span>{{ _trans('My account') }} </span></a></li>

                    @canany(['Chat list','Chat add','Chat edit','Chat delete'])
                    <li><a href="{{ route('owner.chat.messages') }}"><i data-feather="mail"></i><span>{{ _trans('Messages') }}</span></a></li>
                    @endcanany

                    @canany(['Order list','Order add','Order edit','Order delete'])
                    <li><a href="{{ route('order.index') }}"><i data-feather="file-text"></i><span>{{ _trans('Orders') }}</span></a></li>
                    @endcanany
                    <li><a href="{{ route('owner.logout') }}"><i data-feather="log-in"> </i><span>{{ _trans('Logout') }}</span></a></li>
                </ul>
            </li>
        </ul>
    </div>

</div>